// Code generated by hertz generator.

package order_book

import (
	"context"

	order_book "github.com/Mestrace/orderbook/biz/model/tradesoft/exchange/order_book"
	"github.com/cloudwego/hertz/pkg/app"
)

// GetExchangeOrderBook .
// @router exchanges/:exchange_name/order-books [GET]
func GetExchangeOrderBook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order_book.GetExchangeOrderBookReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(order_book.GetExchangeOrderBookResp)

	c.JSON(200, resp)
}

// GetExchangeMetadata .
// @router exchanges/:exchange_name/metadata [GET]
func GetExchangeMetadata(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order_book.GetExchangeMetadataReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(order_book.GetExchangeMetadataResp)

	c.JSON(200, resp)
}

// UpdateExchangeMetadata .
// @router exchanges/:exchange_name/metadata [POST]
func UpdateExchangeMetadata(ctx context.Context, c *app.RequestContext) {
	var err error
	var req order_book.UpdateExchangeMetadataReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(order_book.UpdateExchangeMetadataResp)

	c.JSON(200, resp)
}
