// Code generated by hertz generator.

package order_book

import (
	"fmt"
	"testing"

	order_book "github.com/Mestrace/orderbook/biz/model/tradesoft/exchange/order_book"
	"github.com/cloudwego/hertz/pkg/common/test/assert"
)

func TestUnit_setResponse(t *testing.T) {
	resp := &order_book.GetExchangeMetadataResp{}

	setErrorResponse(resp, fmt.Errorf("set error"))

	assert.DeepEqual(t, resp.BizCode, int32(-1))
	assert.DeepEqual(t, resp.ErrMsg, "set error")
}
