global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "hertz"
    scrape_interval: 1s
    metrics_path: /hertz
    static_configs:
      - targets: ["localhost:9091"]
