// Code generated by hertz generator.

package OrderBook

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exchangesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exchange_nameMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexchangemetadataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateexchangemetadataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexchangeorderbookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _order_booksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getexchangeorderbook_llMw() []app.HandlerFunc {
	// your code...
	return nil
}
