// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	tradesoft_exchange_order_book "github.com/Mestrace/orderbook/biz/router/tradesoft/exchange/order_book"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	tradesoft_exchange_order_book.Register(r)
}
